name: White Paper
highlighter: rouge
description: Alexander Jaeger
intro: A blog covering my work.
logo: logo.png

# Owner/author information
owner:
  name:           Alex Jaeger
  email:          agjaeger@ualr.edu
  # Social networking links used in footer. Update and remove as you like.
  github:
  stackexchange:

sass:
  sass_dir: assets/_sass

include: ['_pages']
