name: White Paper
highlighter: rouge
description: Alexander Jaeger
intro: A blog covering my work.

url: http://www.alexjaeger.org/
##url: http://localhost:4000/

owner:
  name:           Alex Jaeger
  email:          agjaeger@ualr.edu

include: ['_pages', 'assets']

sass:
  style: compressed

theme_mode: 'standard' # choices are 'dark', 'standard', and 'markdown'

navigation:
  - text: Home
    url: /
  - text: Blog
    url: /blog
  - text: Projects
    url: /projects
  - text: Interesting Links
    url: /coollinks
  - text: About Me
    url: /about
    
markdown: kramdown
kramdown:
  input: GFM
